name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7.1.0
        with:
          start: npm start
